name: Pull request

on:
  pull_request:

jobs:
  build:
    name: Pull request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "GITHUB_ACTOR = ${GITHUB_ACTOR}"
          echo "GITHUB_REF = ${GITHUB_REF}"
          echo "GITHUB_REF_TYPE = ${GITHUB_REF_TYPE}"
          echo "GITHUB_SHA = ${GITHUB_SHA}"
          echo "GITHUB_TRIGGERING_ACTOR = ${GITHUB_TRIGGERING_ACTOR}"
          echo "GITHUB_EVENT_NAME = ${GITHUB_EVENT_NAME}"
          echo 'github.actor = ${{ github.actor }}'
          echo 'github.ref = ${{ github.ref }}'
          echo 'github.ref_type = ${{ github.ref_type }}'
          echo 'github.sha = ${{ github.sha }}'
          echo 'github.triggering_actor = ${{ github.triggering_actor }}'
          echo 'github.event_name = ${{ github.event_name }}'
        shell: bash

      - name: Publish
        id: publish
        if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref == 'refs/heads/master' }}
        run: |
          echo 'Publishing...'
        shell: bash
